[build]
[build.environment]
HUGO_VERSION = "0.96.0"
GO_VERSION = "1.18"

[[plugins]]
package = "netlify-plugin-checklinks"
  [plugins.inputs]
  skipPatterns = [ "/_print" ]
  checkExternal = false
  followSourceMaps = true